// <auto-generated />
namespace Events.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class HomePageShopCartReload : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(HomePageShopCartReload));
        
        string IMigrationMetadata.Id
        {
            get { return "201705032203156_HomePageShopCartReload"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
